[package]
name = "rust-translator"
version = "0.1.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.'cfg(target_os = "windows")'.dependencies]
cli-clipboard = "0.2"

[dependencies]
tokio = { version = "1.20", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"
colored = "2.0"
clap = { version = "3.2", features = ["derive"] }
